CREATE TABLE EMPLOYEE(
  EMP_NAME VARCHAR(50),
  EMP_ID NUMBER PRIMARY KEY,
  LOCATION VARCCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) UNIQUE
);

INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
  
