CREATE TABLE EMPLOYEE(
  EMP_NAME VARCHAR(50),
  EMP_ID NUMBER PRIMARY KEY,
  LOCATION VARCCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) UNIQUE
);

INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');
INSERT INTO EMPLOYEE VALUES('UJJWAL', 123, 'DELHI', 'UJJWAL@GMAIL.COM');


SELECT COUNT(NAME) FROM EMPLOYEE;
SELECT MAX(EMP_ID) FROM EMPLOYEE;
SELECT MIN(EMP_ID) FROM EMPLOYEE;
SELECT AVG(EMP_ID) FROM EMPLOYEE;

  
