CREATE TABLE STUDENTS (
    NAME VARCHAR(50) NOT NULL,
    ROLLNO INTEGER PRIMARY KEY,
    CITY VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    AGE INT CHECK (AGE >= 18)
);

INSERT INTO STUDENTS VALUES ('UJJWAL', 100, 'MEERUT', 'ujjwal@example.com', 20);
INSERT INTO STUDENTS VALUES ('RAHUL', 101, 'DELHI', 'rahul@example.com', 21);
INSERT INTO STUDENTS VALUES ('PRIYA', 102, 'MUMBAI', 'priya@example.com', 22);
INSERT INTO STUDENTS VALUES ('ANKIT', 103, 'LUCKNOW', 'ankit@example.com', 23);
INSERT INTO STUDENTS VALUES ('NEHA', 104, 'PUNE', 'neha@example.com', 24);
INSERT INTO STUDENTS VALUES ('ROHAN', 105, 'CHENNAI', 'rohan@example.com', 25);
INSERT INTO STUDENTS VALUES ('SNEHA', 106, 'BANGALORE', 'sneha@example.com', 26);
INSERT INTO STUDENTS VALUES ('AMIT', 107, 'KOLKATA', 'amit@example.com', 27);
INSERT INTO STUDENTS VALUES ('SONIA', 108, 'JAIPUR', 'sonia@example.com', 19);
INSERT INTO STUDENTS VALUES ('VIKAS', 109, 'HYDERABAD', 'vikas@example.com', 18);


SELECT * FROM STUDENTS;

UPDATE STUDENTS SET CITY = 'NOIDA' WHERE ROLLNO = 101;
DELETE FROM STUDENTS WHERE ROLLNO = 102;
ALTER TABLE STUDENTS ADD COLUMN PHONE VARCHAR(15);
ALTER TABLE STUDENTS MODIFY CITY VARCHAR(100);
ALTER TABLE STUDENTS ADD COLUMN CLASS_ID INT;
ALTER TABLE STUDENTS ADD CONSTRAINT fk_class FOREIGN KEY (CLASS_ID) REFERENCES CLASS(CLASS_ID);
INSERT INTO STUDENTS (NAME, ROLLNO, CITY, EMAIL, AGE) VALUES ('ANKIT', 103, 'LUCKNOW', 'ankit@example.com', 23) ON DUPLICATE KEY UPDATE CITY = 'LUCKNOW', AGE = 23;
ALTER TABLE STUDENTS RENAME TO STUDENT_DETAILS;
COMMENT ON TABLE STUDENT_DETAILS IS 'Table storing student personal and academic details';
COMMENT ON COLUMN STUDENT_DETAILS.NAME IS 'Full name of the student';
ALTER TABLE STUDENT_DETAILS DROP COLUMN PHONE;

DROP TABLE STUDENT_DETAILS;
DROP TABLE CLASS;

-- DCL (Data Control Language)

GRANT SELECT, INSERT, UPDATE ON STUDENTS TO user1;
REVOKE INSERT, UPDATE ON STUDENTS FROM user1;
GRANT ALL PRIVILEGES ON STUDENTS TO user2;
REVOKE ALL PRIVILEGES ON STUDENTS FROM user2;

-- TCL (Transaction Control Language)

-- Start a transaction (implicit in most DBs when you run DML)
-- 1. Insert some data
-- 2. SAVEPOINT: mark a point inside a transaction
-- 3. Another insert
-- 4. ROLLBACK TO SAVEPOINT: undo changes after savepoint
-- 5. COMMIT: permanently save all changes
-- After commit, changes cannot be rolled back
INSERT INTO STUDENTS (NAME, ROLLNO, CITY, EMAIL, AGE) VALUES ('RAJ', 110, 'AGRA', 'raj@example.com', 22);
SAVEPOINT sp1;
INSERT INTO STUDENTS (NAME, ROLLNO, CITY, EMAIL, AGE) VALUES ('KARAN', 111, 'SURAT', 'karan@example.com', 23);
ROLLBACK TO sp1;   -- removes KARAN but keeps RAJ
COMMIT;


SELECT COUNT(NAME) FROM STUDENTS;
SELECT MAX(AGE) FROM STUDENTS;
SELECT MIN(AGE) FROM STUDENTS;
SELECT AVG(AGE) FROM STUDENTS;
