CREATE TABLE STUDENTS (
    ROLLNO INTEGER PRIMARY KEY,
    NAME VARCHAR(50),
    CITY VARCHAR(50)
);

CREATE TABLE DEPARTMENT (
    DEPTID INTEGER PRIMARY KEY,
    DEPTNAME VARCHAR(50)
);

INSERT INTO STUDENTS VALUES (100, 'UJJWAL', 'MEERUT');
INSERT INTO STUDENTS VALUES (100, 'UJJWAL', 'MEERUT');
INSERT INTO STUDENTS VALUES (100, 'UJJWAL', 'MEERUT');
INSERT INTO STUDENTS VALUES (100, 'UJJWAL', 'MEERUT');




INSERT INTO STUDENTS VALUES ('RAHUL', 101, 'DELHI', 'rahul@example.com', 21);
INSERT INTO STUDENTS VALUES ('PRIYA', 102, 'MUMBAI', 'priya@example.com', 22);
INSERT INTO STUDENTS VALUES ('ANKIT', 103, 'LUCKNOW', 'ankit@example.com', 23);
INSERT INTO STUDENTS VALUES ('NEHA', 104, 'PUNE', 'neha@example.com', 24);
INSERT INTO STUDENTS VALUES ('ROHAN', 105, 'CHENNAI', 'rohan@example.com', 25);
INSERT INTO STUDENTS VALUES ('SNEHA', 106, 'BANGALORE', 'sneha@example.com', 26);
INSERT INTO STUDENTS VALUES ('AMIT', 107, 'KOLKATA', 'amit@example.com', 27);

SELECT * FROM STUDENTS;
