CREATE TABLE STUDENTS (
    ROLLNO NUMBER PRIMARY KEY,
    NAME VARCHAR(50),
    DEPTID NUMBER
);

CREATE TABLE DEPARTMENT (
    DEPTID NUMBER PRIMARY KEY,
    DEPTNAME VARCHAR(50)
);

INSERT INTO STUDENTS VALUES (1, 'ABC', 101);
INSERT INTO STUDENTS VALUES (2, 'DEF', 102);
INSERT INTO STUDENTS VALUES (3, 'GHI', 103);
INSERT INTO STUDENTS VALUES (4, 'JKL', 104);
INSERT INTO STUDENTS VALUES (5, 'MNO', 105);

INSERT INTO DEPARTMENT VALUES (101, 'IT');
INSERT INTO DEPARTMENT VALUES (102, 'HR');
INSERT INTO DEPARTMENT VALUES (103, 'FINANCE');
INSERT INTO DEPARTMENT VALUES (104, 'HR');
INSERT INTO DEPARTMENT VALUES (105, 'IT');

-- INNER JOIN
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S
INNER JOIN DEPARTMENT D
ON S.DEPTID = D.DEPTID;

-- OUTER JOIN
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENT D ON S.DEPTID = D.DEPTID
UNION
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S
RIGHT JOIN DEPARTMENT D ON S.DEPTID = D.DEPTID;

-- LEFT JOIN
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S
LEFT JOIN DEPARTMENT D
ON S.DEPTID = D.DEPTID;

-- RIGHT JOIN
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S
RIGHT JOIN DEPARTMENT D
ON S.DEPTID = D.DEPTID;

-- CROSS JOIN
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S
CROSS JOIN DEPARTMENT D;

-- THETA JOIN
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S
JOIN DEPARTMENT D
ON S.DEPTID > D.DEPTID;

-- EQUI JOIN
SELECT S.ROLLNO, S.NAME, D.DEPTNAME
FROM STUDENTS S, DEPARTMENT D
WHERE S.DEPTID = D.DEPTID;

-- NATURAL JOIN
SELECT *
FROM STUDENTS
NATURAL JOIN DEPARTMENT;
