CREATE TABLE STUDENTS (
    NAME VARCHAR(50),
    ROLLNO INTEGER PRIMARY KEY,
    CITY VARCHAR(50),
);

CREATE TABLE DEPARTMENT (
    DEPTNAME VARCHAR(50),
    DEPTID INTEGER PRIMARY KEY,
    CITY VARCHAR(50),
    AGE INT CHECK (AGE >= 18)
);

INSERT INTO STUDENTS VALUES ('UJJWAL', 100, 'MEERUT', 'ujjwal@example.com', 20);
INSERT INTO STUDENTS VALUES ('RAHUL', 101, 'DELHI', 'rahul@example.com', 21);
INSERT INTO STUDENTS VALUES ('PRIYA', 102, 'MUMBAI', 'priya@example.com', 22);
INSERT INTO STUDENTS VALUES ('ANKIT', 103, 'LUCKNOW', 'ankit@example.com', 23);
INSERT INTO STUDENTS VALUES ('NEHA', 104, 'PUNE', 'neha@example.com', 24);
INSERT INTO STUDENTS VALUES ('ROHAN', 105, 'CHENNAI', 'rohan@example.com', 25);
INSERT INTO STUDENTS VALUES ('SNEHA', 106, 'BANGALORE', 'sneha@example.com', 26);
INSERT INTO STUDENTS VALUES ('AMIT', 107, 'KOLKATA', 'amit@example.com', 27);
INSERT INTO STUDENTS VALUES ('SONIA', 108, 'JAIPUR', 'sonia@example.com', 19);
INSERT INTO STUDENTS VALUES ('VIKAS', 109, 'HYDERABAD', 'vikas@example.com', 18);

SELECT * FROM STUDENTS;
